### ISSUE TITLE
How to build the yugabyte-db-thirdparty with --no-tcmalloc?

### ISSUE THREAD

**Issue by zhangm365** [yugabyte/yugabyte-db-thirdparty#250]
Hello, @mbautin   and others,

How to build the yugabyte-db-thirdparty with `--no-tcmalloc`, this means to turn off tcmalloc config? The build of yugabyte-db-thirdparty use the cmd:
`./build_thirdparty.sh` 
Is this compilation command using the tcmalloc parameter by default?

Why am I doing this? Because I will get an error when compiling the repository `yugabyte-db` as follows:

`./yb_build.sh --force-run-cmake --no-tcmalloc`

Thanks, 
zhangm365.

**Comment by SrivastavaAnubhav** [comment]
Hi @zhangm365, sorry this got missed. The yugabyte-db-thirdparty repo is used to build thirdparty libraries for the main yugabyte-db build; there is no command to not build  tcmalloc in yugabyte-db-thirdparty. Your command to build yugabyte-db without tcmalloc should work, though it is not tested in our CI so I can see how a compilation failure might not be caught. Could you please open an issue on the main yugabyte-db repository instead? Thanks!

**Comment by zhangm365** [comment]
> Hi @zhangm365, sorry this got missed. The yugabyte-db-thirdparty repo is used to build thirdparty libraries for the main yugabyte-db build; there is no command to not build tcmalloc in yugabyte-db-thirdparty. Your command to build yugabyte-db without tcmalloc should work, though it is not tested in our CI so I can see how a compilation failure might not be caught. Could you please open an issue on the main yugabyte-db repository instead? Thanks!

ok, thanks for your reply.
